# Em caso de sucesso, test de uma rua -- local
POST http://localhost:8080/temperatura HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "cep":"15771034"
}
###
# -----------------------------------------------------------------------------------------------

# Em caso de falha para retornar cep invalido -- local
POST http://localhost:8080/temperatura HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "cep":"15787"
}
###
# -----------------------------------------------------------------------------------------------
# Em caso de cep valido, porém não encontrado da base -- local
POST http://localhost:8080/temperatura HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "cep":"15771411"
}
